class SuraModel {
  String suraNameEn;
  String suraNameAr;
  String versesNumber;
  String suraIndex;

  SuraModel({
    required this.suraNameEn,
    required this.suraNameAr,
    required this.versesNumber,
    required this.suraIndex,
  });

  static List<SuraModel> suras = [
    SuraModel(
      suraNameEn: "Al-Fatiha",
      suraNameAr: "الفاتحه",
      versesNumber: "7",
      suraIndex: "1",
    ),
    SuraModel(
      suraNameEn: "Al-Baqarah",
      suraNameAr: "البقرة",
      versesNumber: "286",
      suraIndex: "2",
    ),
    SuraModel(
      suraNameEn: "Aal-E-Imran",
      suraNameAr: "آل عمران",
      versesNumber: "200",
      suraIndex: "3",
    ),
    SuraModel(
      suraNameEn: "An-Nisa'",
      suraNameAr: "النساء",
      versesNumber: "176",
      suraIndex: "4",
    ),
    SuraModel(
      suraNameEn: "Al-Ma'idah",
      suraNameAr: "المائدة",
      versesNumber: "120",
      suraIndex: "5",
    ),
    SuraModel(
      suraNameEn: "Al-An'am",
      suraNameAr: "الأنعام",
      versesNumber: "165",
      suraIndex: "6",
    ),
    SuraModel(
      suraNameEn: "Al-A'raf",
      suraNameAr: "الأعراف",
      versesNumber: "206",
      suraIndex: "7",
    ),
    SuraModel(
      suraNameEn: "Al-Anfal",
      suraNameAr: "الأنفال",
      versesNumber: "75",
      suraIndex: "8",
    ),
    SuraModel(
      suraNameEn: "At-Tawbah",
      suraNameAr: "التوبة",
      versesNumber: "129",
      suraIndex: "9",
    ),
    SuraModel(
      suraNameEn: "Yunus",
      suraNameAr: "يونس",
      versesNumber: "109",
      suraIndex: "10",
    ),
    SuraModel(
      suraNameEn: "Hud",
      suraNameAr: "هود",
      versesNumber: "123",
      suraIndex: "11",
    ),
    SuraModel(
      suraNameEn: "Yusuf",
      suraNameAr: "يوسف",
      versesNumber: "111",
      suraIndex: "12",
    ),
    SuraModel(
      suraNameEn: "Ar-Ra'd",
      suraNameAr: "الرعد",
      versesNumber: "43",
      suraIndex: "13",
    ),
    SuraModel(
      suraNameEn: "Ibrahim",
      suraNameAr: "إبراهيم",
      versesNumber: "52",
      suraIndex: "14",
    ),
    SuraModel(
      suraNameEn: "Al-Hijr",
      suraNameAr: "الحجر",
      versesNumber: "99",
      suraIndex: "15",
    ),
    SuraModel(
      suraNameEn: "An-Nahl",
      suraNameAr: "النحل",
      versesNumber: "128",
      suraIndex: "16",
    ),
    SuraModel(
      suraNameEn: "Al-Isra",
      suraNameAr: "الإسراء",
      versesNumber: "111",
      suraIndex: "17",
    ),
    SuraModel(
      suraNameEn: "Al-Kahf",
      suraNameAr: "الكهف",
      versesNumber: "110",
      suraIndex: "18",
    ),
    SuraModel(
      suraNameEn: "Maryam",
      suraNameAr: "مريم",
      versesNumber: "98",
      suraIndex: "19",
    ),
    SuraModel(
      suraNameEn: "Ta-Ha",
      suraNameAr: "طه",
      versesNumber: "135",
      suraIndex: "20",
    ),
    SuraModel(
      suraNameEn: "Al-Anbiya",
      suraNameAr: "الأنبياء",
      versesNumber: "112",
      suraIndex: "21",
    ),
    SuraModel(
      suraNameEn: "Al-Hajj",
      suraNameAr: "الحج",
      versesNumber: "78",
      suraIndex: "22",
    ),
    SuraModel(
      suraNameEn: "Al-Mu'minun",
      suraNameAr: "المؤمنون",
      versesNumber: "118",
      suraIndex: "23",
    ),
    SuraModel(
      suraNameEn: "An-Nur",
      suraNameAr: "النّور",
      versesNumber: "64",
      suraIndex: "24",
    ),
    SuraModel(
      suraNameEn: "Al-Furqan",
      suraNameAr: "الفرقان",
      versesNumber: "77",
      suraIndex: "25",
    ),
    SuraModel(
      suraNameEn: "Ash-Shu'ara",
      suraNameAr: "الشعراء",
      versesNumber: "227",
      suraIndex: "26",
    ),
    SuraModel(
      suraNameEn: "An-Naml",
      suraNameAr: "النّمل",
      versesNumber: "93",
      suraIndex: "27",
    ),
    SuraModel(
      suraNameEn: "Al-Qasas",
      suraNameAr: "القصص",
      versesNumber: "88",
      suraIndex: "28",
    ),
    SuraModel(
      suraNameEn: "Al-Ankabut",
      suraNameAr: "العنكبوت",
      versesNumber: "69",
      suraIndex: "29",
    ),
    SuraModel(
      suraNameEn: "Ar-Rum",
      suraNameAr: "الرّوم",
      versesNumber: "60",
      suraIndex: "30",
    ),
    SuraModel(
      suraNameEn: "Luqman",
      suraNameAr: "لقمان",
      versesNumber: "34",
      suraIndex: "31",
    ),
    SuraModel(
      suraNameEn: "As-Sajda",
      suraNameAr: "السجدة",
      versesNumber: "30",
      suraIndex: "32",
    ),
    SuraModel(
      suraNameEn: "Al-Ahzab",
      suraNameAr: "الأحزاب",
      versesNumber: "73",
      suraIndex: "33",
    ),
    SuraModel(
      suraNameEn: "Saba",
      suraNameAr: "سبأ",
      versesNumber: "54",
      suraIndex: "34",
    ),
    SuraModel(
      suraNameEn: "Fatir",
      suraNameAr: "فاطر",
      versesNumber: "45",
      suraIndex: "35",
    ),
    SuraModel(
      suraNameEn: "Ya-Sin",
      suraNameAr: "يس",
      versesNumber: "83",
      suraIndex: "36",
    ),
    SuraModel(
      suraNameEn: "As-Saffat",
      suraNameAr: "الصافات",
      versesNumber: "182",
      suraIndex: "37",
    ),
    SuraModel(
      suraNameEn: "Sad",
      suraNameAr: "ص",
      versesNumber: "88",
      suraIndex: "38",
    ),
    SuraModel(
      suraNameEn: "Az-Zumar",
      suraNameAr: "الزمر",
      versesNumber: "75",
      suraIndex: "39",
    ),
    SuraModel(
      suraNameEn: "Ghafir",
      suraNameAr: "غافر",
      versesNumber: "85",
      suraIndex: "40",
    ),
    SuraModel(
      suraNameEn: "Fussilat",
      suraNameAr: "فصّلت",
      versesNumber: "54",
      suraIndex: "41",
    ),
    SuraModel(
      suraNameEn: "Ash-Shura",
      suraNameAr: "الشورى",
      versesNumber: "53",
      suraIndex: "42",
    ),
    SuraModel(
      suraNameEn: "Az-Zukhruf",
      suraNameAr: "الزخرف",
      versesNumber: "89",
      suraIndex: "43",
    ),
    SuraModel(
      suraNameEn: "Ad-Dukhan",
      suraNameAr: "الدّخان",
      versesNumber: "59",
      suraIndex: "44",
    ),
    SuraModel(
      suraNameEn: "Al-Jathiya",
      suraNameAr: "الجاثية",
      versesNumber: "37",
      suraIndex: "45",
    ),
    SuraModel(
      suraNameEn: "Al-Ahqaf",
      suraNameAr: "الأحقاف",
      versesNumber: "35",
      suraIndex: "46",
    ),
    SuraModel(
      suraNameEn: "Muhammad",
      suraNameAr: "محمد",
      versesNumber: "38",
      suraIndex: "47",
    ),
    SuraModel(
      suraNameEn: "Al-Fath",
      suraNameAr: "الفتح",
      versesNumber: "29",
      suraIndex: "48",
    ),
    SuraModel(
      suraNameEn: "Al-Hujurat",
      suraNameAr: "الحجرات",
      versesNumber: "18",
      suraIndex: "49",
    ),
    SuraModel(
      suraNameEn: "Qaf",
      suraNameAr: "ق",
      versesNumber: "45",
      suraIndex: "50",
    ),
    SuraModel(
      suraNameEn: "Adh-Dhariyat",
      suraNameAr: "الذاريات",
      versesNumber: "60",
      suraIndex: "51",
    ),
    SuraModel(
      suraNameEn: "At-Tur",
      suraNameAr: "الطور",
      versesNumber: "49",
      suraIndex: "52",
    ),
    SuraModel(
      suraNameEn: "An-Najm",
      suraNameAr: "النجم",
      versesNumber: "62",
      suraIndex: "53",
    ),
    SuraModel(
      suraNameEn: "Al-Qamar",
      suraNameAr: "القمر",
      versesNumber: "55",
      suraIndex: "54",
    ),
    SuraModel(
      suraNameEn: "Ar-Rahman",
      suraNameAr: "الرحمن",
      versesNumber: "78",
      suraIndex: "55",
    ),
    SuraModel(
      suraNameEn: "Al-Waqi'a",
      suraNameAr: "الواقعة",
      versesNumber: "96",
      suraIndex: "56",
    ),
    SuraModel(
      suraNameEn: "Al-Hadid",
      suraNameAr: "الحديد",
      versesNumber: "29",
      suraIndex: "57",
    ),
    SuraModel(
      suraNameEn: "Al-Mujadila",
      suraNameAr: "المجادلة",
      versesNumber: "22",
      suraIndex: "58",
    ),
    SuraModel(
      suraNameEn: "Al-Hashr",
      suraNameAr: "الحشر",
      versesNumber: "24",
      suraIndex: "59",
    ),
    SuraModel(
      suraNameEn: "Al-Mumtahina",
      suraNameAr: "الممتحنة",
      versesNumber: "13",
      suraIndex: "60",
    ),
    SuraModel(
      suraNameEn: "As-Saff",
      suraNameAr: "الصف",
      versesNumber: "14",
      suraIndex: "61",
    ),
    SuraModel(
      suraNameEn: "Al-Jumu'a",
      suraNameAr: "الجمعة",
      versesNumber: "11",
      suraIndex: "62",
    ),
    SuraModel(
      suraNameEn: "Al-Munafiqun",
      suraNameAr: "المنافقون",
      versesNumber: "11",
      suraIndex: "63",
    ),
    SuraModel(
      suraNameEn: "At-Taghabun",
      suraNameAr: "التغابن",
      versesNumber: "18",
      suraIndex: "64",
    ),
    SuraModel(
      suraNameEn: "At-Talaq",
      suraNameAr: "الطلاق",
      versesNumber: "12",
      suraIndex: "65",
    ),
    SuraModel(
      suraNameEn: "At-Tahrim",
      suraNameAr: "التحريم",
      versesNumber: "12",
      suraIndex: "66",
    ),
    SuraModel(
      suraNameEn: "Al-Mulk",
      suraNameAr: "الملك",
      versesNumber: "30",
      suraIndex: "67",
    ),
    SuraModel(
      suraNameEn: "Al-Qalam",
      suraNameAr: "القلم",
      versesNumber: "52",
      suraIndex: "68",
    ),
    SuraModel(
      suraNameEn: "Al-Haqqah",
      suraNameAr: "الحاقة",
      versesNumber: "52",
      suraIndex: "69",
    ),
    SuraModel(
      suraNameEn: "Al-Ma'arij",
      suraNameAr: "المعارج",
      versesNumber: "44",
      suraIndex: "70",
    ),
    SuraModel(
      suraNameEn: "Nuh",
      suraNameAr: "نوح",
      versesNumber: "28",
      suraIndex: "71",
    ),
    SuraModel(
      suraNameEn: "Al-Jinn",
      suraNameAr: "الجن",
      versesNumber: "28",
      suraIndex: "72",
    ),
    SuraModel(
      suraNameEn: "Al-Muzzammil",
      suraNameAr: "المزّمّل",
      versesNumber: "20",
      suraIndex: "73",
    ),
    SuraModel(
      suraNameEn: "Al-Muddathir",
      suraNameAr: "المدّثر",
      versesNumber: "56",
      suraIndex: "74",
    ),
    SuraModel(
      suraNameEn: "Al-Qiyamah",
      suraNameAr: "القيامة",
      versesNumber: "40",
      suraIndex: "75",
    ),
    SuraModel(
      suraNameEn: "Al-Insan",
      suraNameAr: "الإنسان",
      versesNumber: "31",
      suraIndex: "76",
    ),
    SuraModel(
      suraNameEn: "Al-Mursalat",
      suraNameAr: "المرسلات",
      versesNumber: "50",
      suraIndex: "77",
    ),
    SuraModel(
      suraNameEn: "An-Naba'",
      suraNameAr: "النبأ",
      versesNumber: "40",
      suraIndex: "78",
    ),
    SuraModel(
      suraNameEn: "An-Nazi'at",
      suraNameAr: "النازعات",
      versesNumber: "46",
      suraIndex: "79",
    ),
    SuraModel(
      suraNameEn: "Abasa",
      suraNameAr: "عبس",
      versesNumber: "42",
      suraIndex: "80",
    ),
    SuraModel(
      suraNameEn: "At-Takwir",
      suraNameAr: "التكوير",
      versesNumber: "29",
      suraIndex: "81",
    ),
    SuraModel(
      suraNameEn: "Al-Infitar",
      suraNameAr: "الإنفطار",
      versesNumber: "19",
      suraIndex: "82",
    ),
    SuraModel(
      suraNameEn: "Al-Mutaffifin",
      suraNameAr: "المطفّفين",
      versesNumber: "36",
      suraIndex: "83",
    ),
    SuraModel(
      suraNameEn: "Al-Inshiqaq",
      suraNameAr: "الإنشقاق",
      versesNumber: "25",
      suraIndex: "84",
    ),
    SuraModel(
      suraNameEn: "Al-Buruj",
      suraNameAr: "البروج",
      versesNumber: "22",
      suraIndex: "85",
    ),
    SuraModel(
      suraNameEn: "At-Tariq",
      suraNameAr: "الطارق",
      versesNumber: "17",
      suraIndex: "86",
    ),
    SuraModel(
      suraNameEn: "Al-A'la",
      suraNameAr: "الأعلى",
      versesNumber: "19",
      suraIndex: "87",
    ),
    SuraModel(
      suraNameEn: "Al-Ghashiyah",
      suraNameAr: "الغاشية",
      versesNumber: "26",
      suraIndex: "88",
    ),
    SuraModel(
      suraNameEn: "Al-Fajr",
      suraNameAr: "الفجر",
      versesNumber: "30",
      suraIndex: "89",
    ),
    SuraModel(
      suraNameEn: "Al-Balad",
      suraNameAr: "البلد",
      versesNumber: "20",
      suraIndex: "90",
    ),
    SuraModel(
      suraNameEn: "Ash-Shams",
      suraNameAr: "الشمس",
      versesNumber: "15",
      suraIndex: "91",
    ),
    SuraModel(
      suraNameEn: "Al-Lail",
      suraNameAr: "الليل",
      versesNumber: "21",
      suraIndex: "92",
    ),
    SuraModel(
      suraNameEn: "Ad-Duha",
      suraNameAr: "الضحى",
      versesNumber: "11",
      suraIndex: "93",
    ),
    SuraModel(
      suraNameEn: "Ash-Sharh",
      suraNameAr: "الشرح",
      versesNumber: "8",
      suraIndex: "94",
    ),
    SuraModel(
      suraNameEn: "At-Tin",
      suraNameAr: "التين",
      versesNumber: "5",
      suraIndex: "95",
    ),
    SuraModel(
      suraNameEn: "Al-Alaq",
      suraNameAr: "العلق",
      versesNumber: "19",
      suraIndex: "96",
    ),
    SuraModel(
      suraNameEn: "Al-Qadr",
      suraNameAr: "القدر",
      versesNumber: "5",
      suraIndex: "97",
    ),
    SuraModel(
      suraNameEn: "Al-Bayyina",
      suraNameAr: "البينة",
      versesNumber: "8",
      suraIndex: "98",
    ),
    SuraModel(
      suraNameEn: "Az-Zalzalah",
      suraNameAr: "الزلزلة",
      versesNumber: "8",
      suraIndex: "99",
    ),
    SuraModel(
      suraNameEn: "Al-Adiyat",
      suraNameAr: "العاديات",
      versesNumber: "11",
      suraIndex: "100",
    ),
    SuraModel(
      suraNameEn: "Al-Qari'a",
      suraNameAr: "القارعة",
      versesNumber: "11",
      suraIndex: "101",
    ),
    SuraModel(
      suraNameEn: "At-Takathur",
      suraNameAr: "التكاثر",
      versesNumber: "8",
      suraIndex: "102",
    ),
    SuraModel(
      suraNameEn: "Al-Asr",
      suraNameAr: "العصر",
      versesNumber: "3",
      suraIndex: "103",
    ),
    SuraModel(
      suraNameEn: "Al-Humazah",
      suraNameAr: "الهمزة",
      versesNumber: "9",
      suraIndex: "104",
    ),
    SuraModel(
      suraNameEn: "Al-Fil",
      suraNameAr: "الفيل",
      versesNumber: "5",
      suraIndex: "105",
    ),
    SuraModel(
      suraNameEn: "Quraysh",
      suraNameAr: "قريش",
      versesNumber: "4",
      suraIndex: "106",
    ),
    SuraModel(
      suraNameEn: "Al-Ma'un",
      suraNameAr: "الماعون",
      versesNumber: "6",
      suraIndex: "107",
    ),
    SuraModel(
      suraNameEn: "Al-Kawthar",
      suraNameAr: "الكوثر",
      versesNumber: "3",
      suraIndex: "108",
    ),
    SuraModel(
      suraNameEn: "Al-Kafirun",
      suraNameAr: "الكافرون",
      versesNumber: "6",
      suraIndex: "109",
    ),
    SuraModel(
      suraNameEn: "An-Nasr",
      suraNameAr: "النصر",
      versesNumber: "3",
      suraIndex: "110",
    ),
    SuraModel(
      suraNameEn: "Al-Masad",
      suraNameAr: "المسد",
      versesNumber: "5",
      suraIndex: "111",
    ),
    SuraModel(
      suraNameEn: "Al-Ikhlas",
      suraNameAr: "الإخلاص",
      versesNumber: "4",
      suraIndex: "112",
    ),
    SuraModel(
      suraNameEn: "Al-Falaq",
      suraNameAr: "الفلق",
      versesNumber: "5",
      suraIndex: "113",
    ),
    SuraModel(
      suraNameEn: "An-Nas",
      suraNameAr: "الناس",
      versesNumber: "6",
      suraIndex: "114",
    ),
  ];
}
